version: '3'

services:
  web:
    build:
      dockerfile: ./web/docker/Dockerfile
      context: ./
    command: bash -c "export DJANGO_SETTINGS_MODULE=AutoBot.settings && python -c 'from bot.conf import set_webhook; set_webhook()'; gunicorn AutoBot.wsgi:application --bind 0.0.0.0:8000"
    environment:
     - PYTHONUNBUFFERED=TRUE
    volumes:
      - .:/AutoBot
    ports:
      - "8002:8000"
    networks:
      - app
    depends_on:
      - db

  db:
    image: mysql:8.0.33
    ports:
      - '3123:3306'
    environment:
      MYSQL_DATABASE: 'AutoBot'
      MYSQL_ROOT: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./web/mysql/data:/var/lib/mysql
      - ./web/mysql/dump:/dump
    networks:
      - app

  nginx:
    build: ./web/nginx
    volumes:
      - .:/AutoBot
    ports:
      - 1223:80
    depends_on:
      - web
    networks:
      - app

networks:
  app:
    driver: bridge
