version: '3'

services:
  web:
    build:
      dockerfile: ./web/docker/Dockerfile
      context: ./
    environment:
     - PYTHONUNBUFFERED=TRUE
    volumes:
      - .:/AutoBot
    ports:
      - "8002:8000"
    networks:
      - app
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  db:
    image: mysql:8.0.33
    ports:
      - '3123:3306'
    environment:
      MYSQL_DATABASE: 'AutoBot'
      MYSQL_ROOT: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./web/mysql/data:/var/lib/mysql
      - ./web/mysql/dump:/dump
    networks:
      - app

  redis:
    image: "redis:alpine"
    networks:
      - app

  celery:
    build:
      context: ./
      dockerfile: ./web/docker/Dockerfile
    command: celery -A AutoBot worker --loglevel=info
    volumes:
      - .:/AutoBot
    networks:
      - app
    depends_on:
      - redis
      - web

  celery-beat:
    build:
      context: ./
      dockerfile: ./web/docker/Dockerfile
    command: celery -A AutoBot beat -l info --scheduler django_celery_beat.schedulers.DatabaseScheduler
    volumes:
      - .:/AutoBot
    networks:
      - app
    depends_on:
      - redis
      - celery
      - web

networks:
  app:
    driver: bridge
