# Generated by Django 3.1.1 on 2024-05-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_contacts_contactslink_preference_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='question',
            new_name='preference',
        ),
    ]
